---
# hosts.yaml

all:
  children:
    ungrouped:
      hosts:
        ansible:
          ansible_host: 192.168.99.10
        client1:
          ansible_host: 192.168.99.11
        client2:
          ansible_host: 192.168.99.12 
